/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon {
  'code' : string,
  'createdAt' : bigint,
  'discountPct' : bigint,
}
export interface Member {
  'age' : string,
  'weight' : string,
  'height' : string,
  'endDate' : bigint,
  'city' : string,
  'goal' : string,
  'createdAt' : bigint,
  'plan' : string,
  'fullName' : string,
  'referredBy' : string,
  'whatsappNo' : string,
  'startDate' : bigint,
}
export interface _SERVICE {
  'addCoupon' : ActorMethod<[string, bigint], boolean>,
  'deleteCoupon' : ActorMethod<[string], boolean>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getMember' : ActorMethod<[string], [] | [Member]>,
  'getReferralCount' : ActorMethod<[string], bigint>,
  'registerMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      string,
    ],
    boolean
  >,
  'updateMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
    ],
    boolean
  >,
  'validateCoupon' : ActorMethod<[string], [] | [bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];