/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Member = IDL.Record({
  'age' : IDL.Text,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'endDate' : IDL.Int,
  'city' : IDL.Text,
  'goal' : IDL.Text,
  'createdAt' : IDL.Int,
  'plan' : IDL.Text,
  'fullName' : IDL.Text,
  'referredBy' : IDL.Text,
  'whatsappNo' : IDL.Text,
  'startDate' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
  'getReferralCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'registerMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Int,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Member = IDL.Record({
    'age' : IDL.Text,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'endDate' : IDL.Int,
    'city' : IDL.Text,
    'goal' : IDL.Text,
    'createdAt' : IDL.Int,
    'plan' : IDL.Text,
    'fullName' : IDL.Text,
    'referredBy' : IDL.Text,
    'whatsappNo' : IDL.Text,
    'startDate' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getMember' : IDL.Func([IDL.Text], [IDL.Opt(Member)], ['query']),
    'getReferralCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'registerMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Int,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };